project_id = "nlgakvmxxuoocgkfdkxd"

[functions.hard-delete-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.child-insights]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.restore-user]
verify_jwt = false

[functions.recognize-food]
verify_jwt = false
